play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]
  motions:

    head_tour_fast:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: head_tour_fast
        usage: demo
        description: 'head_tour_fast'

    head_pan_tilted:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, -0.2]
        time_from_start: 2.0
      - positions: [-0.7, -0.2]
        time_from_start: 4.0
      - positions: [0.0, 0.2]
        time_from_start: 6.0
      meta:
        name: head_pan_tilted
        usage: demo
        description: 'head_pan_tilted'

    head_tilt_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, -0.7]
        time_from_start: 2.0
      meta:
        name: head_tilt_down
        usage: demo
        description: 'head_tilt_down'

    head_normal:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 1.0     
      meta:
        name: head_normal
        usage: demo
        description: 'head_normal'